version: "2"
services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app-tier  

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - app-tier
      
  networks:
  app-tier:
    driver: bridge    
    
