version: "3"
services:
  app:
    build:
       context: ./app
    ports:
      - "5001:5000"
    networks:
      - my-network
    depends_on:
      - db  
   
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knights
      MYSQL_USER: root
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    
