version: "3"
services:
  app:
    build:
       context: ./app
  
    ports:
      - "5001:5000"
    networks:
      - my-network
    depends_on:
      - db  
   
  db:
    image: mysql:5.7
    ports:
      - "3200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    
