version: "3"
services:
  app:
    build:
       context: ./app
    ports:
      - "5001:5000"
    links:
      - db  
   
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    
